language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhmv

matrix:
  allow_failures:
    - php: hhmv

before_script:
  - composer self-update
  - composer install --dev -o
  - mkdir tests/files

script: phpunit --coverage-text --coverage-clover /tmp/flysystem/coverage.xml